### Why Numpy?

In [1]:
#import relevant libraries
import numpy as np
import time

#### An attempt to prove that numpy is faster compared to lists by adding 2 lists and 2 arrays and measuring the speed of execution

In [2]:
#initialize size of the numbers to be added(1000000)
size = 1000000

In [3]:
#create 2 lists
lst1 = range(size)
lst2 = range(size)

In [4]:
#create 2 numpy arrays
nparr1 = np.arange(size)
nparr2 = np.arange(size)

In [5]:
#determine the speed of adding numbers in the 2 lists
lst_time = time.time()
list_sum = [(x+y) for x, y in zip(lst1, lst2)]
print("sum of lists : ")
print((time.time() - lst_time) * 1000 )

sum of lists : 
270.10464668273926


In [9]:
#determine the speed of adding same numbers in 2 numpy arrays
np_time = time.time()
np_sum = nparr1 + nparr2
print("sum of nparrays")
print((time.time() - np_time)* 1000)

sum of nparrays
11.456012725830078


##### creating numpy arrays - refer to the notes in NumPy1a, NumPy1b, AND NumPy1c for more 

In [20]:
arr_a = np.array([1,2,3])
arr_a

array([1, 2, 3])

In [21]:
type(arr_a)

numpy.ndarray

In [22]:
list_a = [1,2,3,4]
list_array = np.array(list_a)
list_array

array([1, 2, 3, 4])

In [24]:
num10 = np.arange(0,10)
num10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
rand1 = np.random.random((2,2))
rand1

array([[0.38174153, 0.34175754],
       [0.91679287, 0.43569925]])

In [35]:
datatyp_arr = np.array([[1,2,3], [1,2,3]], dtype = np.int32)
datatyp_arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [36]:
npzeros = np.zeros((2,2))
npzeros

array([[0., 0.],
       [0., 0.]])

In [37]:
npones = np.ones((3,2))
npones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
npones.shape

(3, 2)

In [39]:
npones.size

6

In [40]:
npones3 = np.ones((3,3,3))
npones3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
2 * npones3

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])