## Indexing

A one-dimensional NumPy array can be indexed in exactly the same way as a Python list:

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
a[1]

2

In [6]:
a[-1]

5

When working with two(or more)-dimensional arrays, the syntax is as follows:

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To access the second row:

In [8]:
a[1]

array([4, 5, 6])

To access the second column:

In [9]:
a[:, 1]

array([2, 5, 8])

Note that here the first dimension is indicated as `:` which means "all rows".

## Conditional indexing

One can select certain values in an array, based on some criterion (recall one can do the same with data in a Python list using list comprehension).

Suppose we needed all even numbers from a one-dimensional array:

In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

First we construct an array that is the result of checking a condition on each element of the original array:

In [11]:
condition = a%2 == 0
condition

array([False,  True, False,  True, False,  True, False,  True, False])

Here, we've created a NumPy array that holds the results of checking the condition (the value divides by 2 without any remainder) applied to every element of the `a` array. For example, the second element in the `condition` array is `True`, because `2%2 == 0` evaluates to `True`.

The `condition` array has the same shape as `a`. Now we can use the `condition` array as an index for `a`. Those elements in `a` that correspond to `True` values in `condition` will be kept, all others will be dropped:

In [12]:
a[condition]

array([2, 4, 6, 8])

One can apply more complex conditions, using parentheses and operators `&` ("and") and `|` ("or"). For example, filter elements that are multiples of either 2 or 3:

In [13]:
condition = (a%2 == 0) & (a%3 == 0)
condition

array([False, False, False, False, False,  True, False, False, False])

In [14]:
a[condition]

array([6])

Another way to apply complex conditions is to **vectorize** a Python function, which implements the condition-checking (and possibly some other manipulations with the variables to be checked): 

In [15]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
def my_func(x):
    """The function that checks if a condition applies to an input value and returns a Boolean
    """
    return x%2 == 0 or x%3 == 0 or x == 1

Vectorize the function:

In [17]:
my_func_vec = np.vectorize(my_func)

Now when given an array as an input argument, it will efficiently apply `my_func` to each element in the array.

In [18]:
my_func_vec(a)

array([ True,  True,  True,  True, False,  True, False,  True,  True])

So it can be used to filter elements from an array based on the condition:

In [19]:
a[my_func_vec(a)]

array([1, 2, 3, 4, 6, 8, 9])

## Slicing

Slicing a NumPy array works using syntax similar to indexing:

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Use `x:y` to indicate a range of columns or rows between `x` and `y` (including `x` but excluding `y`), and `:` to indicate all columns or all rows.

For example, to retrieve the first two rows, all columns in `a`:

In [21]:
a[0:2, :]       

array([[1, 2, 3],
       [4, 5, 6]])

The zero in the range can be omitted:

In [22]:
a[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

Similarly, one can omit the index of the last row. E.g., retrieving the last two rows, all columns in `a`:

In [23]:
a[-2:, :]

array([[4, 5, 6],
       [7, 8, 9]])

The same applies to a range of columns. E.g., retrieving all rows, the first two columns:

In [24]:
a[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

All rows, the last two columns:

In [25]:
a[:, -2:]

array([[2, 3],
       [5, 6],
       [8, 9]])

## Manipulating arrays

NumPy can efficiently **transpose** a matrix, using the `transpose` method or the `T` attribute of the array:

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

An array can be **resized**, that is, all elements can be arranged into a different shape. For example, a 3x3 array can be arranged into a 1x9 array, using the `resize` method and supplying a tuple that describes the desired new shape for the array:

In [29]:
a.shape

(3, 3)

In [30]:
a.resize((1, 9))

In [31]:
a.shape

(1, 9)

Note that the operation is performed **in-place**, that is, the original array itself is changed. This is useful in cases when the array is very large and creating a new, reshaped array is prohibitive in terms of computer memory.

The **reshape** method does the same as `resize`, but keeps the original array unchanged and returns a new array:

In [46]:
a.shape

(3, 3)

In [53]:
b = a.reshape((1, 9))

In [54]:
a.shape

(3, 3)

In [55]:
b.shape

(1, 9)

If one tries to resize or reshape an array to an incompatible shape (i.e., such that the size of the original array is not equal to the required number of rows multiplied by the required number of columns), a ValueError is thrown:

In [56]:
a.reshape((5, 5))

ValueError: cannot reshape array of size 9 into shape (5,5)